### PR TITLE
Fix on Ruby 2.2

### PR DESCRIPTION
**Pull request by robredpath**
When attempting to install using Ruby 2.2:
````
root@litespeed-test [/usr/local/wwwh]# gem install lumberg
Building native extensions.  This could take a while...
ERROR:  Error installing lumberg:
        ERROR: Failed to build gem native extension.

    /usr/local/wwwh/bin/ruby -r ./siteconf20150119-26447-1e34viz.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
In file included from generator.c:1:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175: warning: initialization makes integer from pointer without a cast
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/wwwh/lib/ruby/gems/2.2.0/gems/json-1.7.7 for inspection.
Results logged to /usr/local/wwwh/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/json-1.7.7/gem_make.out
````

See https://github.com/flori/json/pull/231 for why 1.8.2 is the magic version.

### CODE REVIEW

**Comment by boone** [comment]
@robredpath can you add Ruby 2.2.0 to the .travis.yml?

**Comment by robredpath** [comment]
````
root@litespeed-test [/usr/local/wwwh]# gem install lumberg-2.0.0.pre21.gem 
Successfully installed lumberg-2.0.0.pre21
1 gem installed
````

^^ when installing modified as per this PR

**Comment by ruyrocha** [comment]
:cake:

**Comment by fabiokr** [comment]
:+1:

**Comment by boone** [comment]
:+1: @robredpath can you squash?

**Comment by robredpath** [comment]
^^ have I done it right? Never squashed before!

**Comment by boone** [comment]
@robredpath there should be only one commit if it worked right. Try this:

`git rebase -i master`

In your editor, leave the first entry and change the prefix of the others from `pick` to `f` for fixup.

Save/close out of that screen.

Now if you look at `git log` you should only see one commit for your changes. If that worked, finally run this:

`git push -f` and that will overwrite the commits here with the new single commit.

**Comment by robredpath** [comment]
There we go! Thanks @boone :)

**Comment by boone** [comment]
@robredpath looks good :+1:

**Pull request merged**
